import { Inter } from 'next/font/google'
import '../globals.css'
import Header from '../componnent/Header'
import Footer from '../componnent/Footer'
import Trands from '../componnent/Trands'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} no-scrollbar`}>
        <Header/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
